-- 1е задание
SELECT PULPIT_NAME
	FROM PULPIT, FACULTY
	WHERE FACULTY.FACULTY = PULPIT.FACULTY AND
	FACULTY.FACULTY IN 
		(SELECT FACULTY FROM PROFESSION WHERE(PROFESSION_NAME LIKE '%технология%'))

-- 2е задание
SELECT PULPIT_NAME 
	FROM PULPIT INNER JOIN FACULTY
	ON FACULTY.FACULTY = PULPIT.FACULTY AND
	FACULTY.FACULTY IN 
		(SELECT FACULTY FROM PROFESSION WHERE(PROFESSION_NAME LIKE '%технология%'))

-- 3е задание
SELECT PULPIT_NAME 
	FROM PULPIT INNER JOIN FACULTY
	ON FACULTY.FACULTY = PULPIT.FACULTY 
		INNER JOIN PROFESSION
		ON PROFESSION.FACULTY = FACULTY.FACULTY WHERE PROFESSION.PROFESSION_NAME LIKE '%технология%'
	--FACULTY.FACULTY IN 
	--	(SELECT FACULTY FROM PROFESSION WHERE(PROFESSION_NAME LIKE '%технология%'))