use UNIVER;
	
    SELECT a.AUDITORIUM
		FROM AUDITORIUM a except
	(select a.AUDITORIUM from TIMETABLE t, AUDITORIUM a where t.AUDITORIUM = a.AUDITORIUM and t.LESSON = 1);


    SELECT AUDITORIUM
		FROM AUDITORIUM a except
    (select a.AUDITORIUM from TIMETABLE t, AUDITORIUM a where t.DAY_NAME = 'пн' and a.AUDITORIUM = t.AUDITORIUM);


    SELECT distinct te.TEACHER_NAME, T1.DAY_NAME, T1.LESSON
    FROM TEACHER te, TIMETABLE T1, TIMETABLE T2 except
    (
		SELECT distinct te.TEACHER_NAME, t.DAY_NAME, t.LESSON
		FROM TEACHER te, TIMETABLE t, TIMETABLE t2
		where te.TEACHER = t.TEACHER and t.DAY_NAME = t2.DAY_NAME and t.LESSON != t2.LESSON
	);


    SELECT distinct G.IDGROUP, t.DAY_NAME, t.LESSON
    FROM GROUPS G, TIMETABLE t, TIMETABLE t2 except
    (
		SELECT distinct G.IDGROUP, t.DAY_NAME, t.LESSON
		FROM GROUPS G, TIMETABLE t, TIMETABLE t2
		WHERE G.IDGROUP = t.IDGROUP and t.DAY_NAME = t2.DAY_NAME and t.LESSON != t2.LESSON
	)ORDER BY G.IDGROUP, t.DAY_NAME desc, t.LESSON;