
use UNIVER


-- Свободные аудитории
select AUDITORIUM.AUDITORIUM_NAME, WEEKDAYS.[NAME], TIMESPACES.STARTTIME 
from (AUDITORIUM cross join TIMESPACES cross join WEEKDAYS) 
	left outer join TIMETABLE 
	on AUDITORIUM.AUDITORIUM = TIMETABLE.AUDITORIUM AND TIMESPACES.ID = TIMETABLE.ID_UROKA
where TIMETABLE.ID_UROKA is null 
order by AUDITORIUM.AUDITORIUM_NAME,  TIMESPACES.STARTTIME



-- Занятые аудитории
select AUDITORIUM.AUDITORIUM_NAME, TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME, TIMETABLE.IDGROUP 
from (AUDITORIUM cross join TIMESPACES cross join WEEKDAYS) inner join TIMETABLE on AUDITORIUM.AUDITORIUM = TIMETABLE.AUDITORIUM
AND TIMESPACES.ID = TIMETABLE.ID_UROKA 
order by AUDITORIUM.AUDITORIUM_NAME, TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME

-- Оналичие «окон» у пгруппах.
select GROUPS.IDGROUP,TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME -- окна у групп
from (GROUPS cross join TIMESPACES cross join WEEKDAYS) 
left outer join TIMETABLE 
on GROUPS.IDGROUP = TIMETABLE.IDGROUP AND TIMESPACES.ID = TIMETABLE.ID_UROKA 
where TIMETABLE.IDGROUP is null
order by GROUPS.IDGROUP, TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME

-- наличие «окон» у преподавателей и 
select TEACHER.TEACHER_NAME, TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME -- окна у преподов
from (TEACHER cross join TIMESPACES cross join WEEKDAYS) 
left outer join TIMETABLE 
on TEACHER.TEACHER_NAME = TIMETABLE.TEACHER AND TIMESPACES.ID = TIMETABLE.ID_UROKA
where TIMETABLE.IDGROUP is null
order by TEACHER.TEACHER, TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME

-- занятые пары у студентов
select GROUPS.IDGROUP,  TIMESPACES.STARTTIME 
from (GROUPS cross join TIMESPACES cross join WEEKDAYS) left outer join TIMETABLE on GROUPS.IDGROUP = TIMETABLE.IDGROUP
where TIMESPACES.ID = TIMETABLE.ID_UROKA 
order by GROUPS.IDGROUP, TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME

 -- занятые пары у преподов
select TEACHER.TEACHER_NAME,TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME
from (TEACHER cross join TIMESPACES cross join WEEKDAYS) 
left outer join TIMETABLE 
on TEACHER.TEACHER_NAME = TIMETABLE.TEACHER AND TIMESPACES.ID = TIMETABLE.ID_UROKA
where TIMETABLE.IDGROUP is not null
order by TEACHER.TEACHER, TIMETABLE.DAY_NAME, TIMESPACES.STARTTIME
